# Generated by Django 3.2.16 on 2023-01-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='fields_not_equal',
        ),
    ]
